Updating Third Party Bots information
LivePersonInc/knowledge-center-archive pull request #370
Opened 2021-05-27 16:56 UTC by jgonzalezal

2021-05-28 08:02 UTC, ahuppert requested changes
Could you align the existing vendors a bit better with the current developers documentation? (see my comments)
Also do you have in mind the confluence page mentioned in the jira task?

2021-05-28 08:02 UTC, ahuppert commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   6. [Microsoft Bot Framework](https://developers.liveperson.com/bot-connectors-microsoft-bot-framework.html)
Name and Link to the vendor are outdated (link still works but is not the most recent one)

```suggestion
   6. [Microsoft Direct Line](https://developers.liveperson.com/third-party-bots-microsoft-direct-line-introduction.html)
```

2021-05-28 08:02 UTC, ahuppert commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   7. [Custom third-party Bots](https://developers.liveperson.com/bot-connectors-custom-third-party-bots.html)
Same here
```suggestion
   7. [Custom Integration](https://developers.liveperson.com/third-party-bots-custom-integration.html)
```

2021-05-28 08:02 UTC, ahuppert commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
>     1. [Watson Assistant](https://developers.liveperson.com/bot-connectors-ibm-watson-assistant.html)
```suggestion
   1. [IBM Watson Assistant](https://developers.liveperson.com/bot-connectors-ibm-watson-assistant.html)
```

2021-05-28 08:02 UTC, ahuppert commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   2. [Watson Assistant V2](https://developers.liveperson.com/third-party-bots-ibm-watson-assistant-version-2.html)
```suggestion
   2. [IBM Watson Assistant Version 2](https://developers.liveperson.com/third-party-bots-ibm-watson-assistant-version-2.html)
```

2021-05-28 08:02 UTC, ahuppert commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   3. [Dialogflow ES](https://developers.liveperson.com/third-party-bots-google-dialogflow-es-introduction.html)
```suggestion
   3. [Google Dialogflow ES](https://developers.liveperson.com/third-party-bots-google-dialogflow-es-introduction.html)
```

2021-05-28 08:02 UTC, ahuppert commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   4. [Dialogflow CX](https://developers.liveperson.com/third-party-bots-google-dialogflow-cx.html)
```suggestion
   4. [Google Dialogflow CX](https://developers.liveperson.com/third-party-bots-google-dialogflow-cx.html)
```

2021-05-28 11:58 UTC, jgonzalezal commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   4. [Dialogflow CX](https://developers.liveperson.com/third-party-bots-google-dialogflow-cx.html)
Done

2021-05-28 11:58 UTC, jgonzalezal commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   3. [Dialogflow ES](https://developers.liveperson.com/third-party-bots-google-dialogflow-es-introduction.html)
Done

2021-05-28 11:59 UTC, jgonzalezal commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   2. [Watson Assistant V2](https://developers.liveperson.com/third-party-bots-ibm-watson-assistant-version-2.html)
Done

2021-05-28 11:59 UTC, jgonzalezal commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
>     1. [Watson Assistant](https://developers.liveperson.com/bot-connectors-ibm-watson-assistant.html)
Done

2021-05-28 11:59 UTC, jgonzalezal commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   7. [Custom third-party Bots](https://developers.liveperson.com/bot-connectors-custom-third-party-bots.html)
Done

2021-05-28 11:59 UTC, jgonzalezal commented on pages/documents/Bots & Automation/Third Party Bot Connectors.md
> +   6. [Microsoft Bot Framework](https://developers.liveperson.com/bot-connectors-microsoft-bot-framework.html)
Done

2021-05-28 12:02 UTC, jgonzalezal commented
@ahuppert suggentions addressed

2021-05-28 14:22 UTC, ahuppert approved these changes

2021-05-31 06:57 UTC, fahimmahmoodmir approved these changes

2021-05-31 11:20 UTC, merged